### ISSUE TITLE
Allow scheduling for different semesters

### ISSUE THREAD

**Issue by Tungpm** [Kuree/scheduleit#10] opened 2016-03-14 03:47 UTC
Specifically, allow user to check and schedule courses for arbitrary semester, instead of only the next immediate semester.

**Comment by Kuree** [comment] 2016-03-21 22:51
I'll add that. Very likely it will be added with #9. I'm thinking to redo the entire UI using VueJS or react. The current implementation is very messy due to the heavy usage of JQuery. Let me know if you you have any suggestions.

**Comment by Tungpm** [comment] 2016-03-24 02:40
To serve advising week and course selection coming up next week, is it possible for you to make a quick fix, and add a simple 2 item drop down menu with semester choices and update the server code accordingly?

**Comment by Kuree** [comment] 2016-03-24 02:42
There is no server code: everything is hosted statically on Github. I'll work on it and hopefully I can finish it by the end of this week.

**Comment by Tungpm** [comment] 2016-03-24 02:44
if you don't mind, I can work on it quickly as well (I'm having some free time at the moment)

**Comment by Kuree** [comment] 2016-03-24 02:49
Sure. For the web crawling part, you just need to change the date in the requests query. Beware that it will flush all the data files so you might need to change the saving process as well. Ideally you can create a config JSON at the root of data folder and contains the information of each school and school year. Then on page load you can read it and decide which one to load.

For the UI part I'm thinking to add a icon at top right corner with a popup to choose which school and class year to use.

gh-page branch is used to host all the web files and you can see the data files there. Let me know if you have any questions and very likely I will work on it tomorrow morning.

**Comment by Kuree** [comment] 2016-03-25 21:06
Finished with 36afdde. It's still under test and you can check out the branch here: https://github.com/Kuree/scheduleit/tree/term_test. Just use any static file server to host it and you should be able to see the change. Let me know if you find any bugs. Close this issue for now.

**Closed as completed by Kuree** 2016-03-25 21:06 UTC

**Comment by Tungpm** [comment] 2016-03-26 01:13
I tried running it without success. 1. After installing BeautifulSoup, it seems like I still have the parse html5lib missing. 2. After changing to a different parser: html.parser, I still could not run it (All departments return error. I tried with different original term parameter to no success)

**Comment by Kuree** [comment] 2016-03-26 01:20
It might caused by missing libraries. I committed all the pip library used in the project in that branch. Try use a virtualenv and install them. The term arg I used was 201701 and 201705 respectively. 

That term_test branch should have all the data files needed already by the way.

**Comment by Tungpm** [comment] 2016-03-26 01:22
So i can just static host the index.html then?

**Comment by Kuree** [comment] 2016-03-26 01:23
Yes, for that branch. It will be merged to gh-pages if all the bugs are discovered and fixed.

**Comment by Tungpm** [comment] 2016-03-26 06:03
After jumping through some hoops, I finally get it to run so kudos.

Some issues/suggestions:
Download doesn't seem to work with this version, probably due to the course
information not populated somewhere?
For the case of the course CSCI 379 in Spring 2017 there are 2 things: i.
Session 01 and 02 have different name/description/instructor but in the
drop down, it only shows the info for 01. ii. Should think of a way to let
users have some preference of which session to take (improvement, not
crucial).
ᐧ

**Comment by Kuree** [comment] 2016-03-26 14:18
1) Download function is handled by another webpage, although it is nested in an iframe in the main page. I just realized that I forgot to change the code querying course data inside the download page. I'll fix it as soon as possible.

2) This is a very good suggestion. I will add it in the future, but for now the current implementation is good enough to run. If you want a specific session, you need to use CRN directly in the input box.

**Comment by Kuree** [comment] 2016-03-26 14:37
1) fixed with 35fd6fd9d4b139f883c8ab63c7913832b30c921f
